controller_list:
  - name: fake_base_controller
    type: $(arg fake_execution_type)
    joints:
      - translate_x
      - translate_y
      - rotate_z
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - kinova_joint_1
      - kinova_joint_2
      - kinova_joint_3
      - kinova_joint_4
      - kinova_joint_5
      - kinova_joint_6
      - kinova_joint_7
  - name: fake_end_effector_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: initial_pose_arm
  - group: end_effector
    pose: initial_pose_gripper