base_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - translate_x
  gains:
    translate_x:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kinova_joint_1
    - kinova_joint_2
    - kinova_joint_3
    - kinova_joint_4
    - kinova_joint_5
    - kinova_joint_6
    - kinova_joint_7
  gains:
    kinova_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kinova_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kinova_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kinova_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kinova_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kinova_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    kinova_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - finger_joint
  gains:
    finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1